"""init schema v0.1 final — extensions, 9 tables, triggers, indexes

Revision ID: 0001_init
Revises:
Create Date: 2026-06-25 18:16:26.437463

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_init"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ===== Extensions =====
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")      # pgvector
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")    # full-text tiếng Việt (bỏ dấu)
    # F5: google_ml_integration only on Cloud SQL (flag cloudsql.enable_google_ml_integration).
    # Catches expected local-dev cases; surfaces unexpected errors with SQLERRM.
    op.execute(
        "DO $$ BEGIN "
        "  CREATE EXTENSION IF NOT EXISTS google_ml_integration; "
        "EXCEPTION "
        "  WHEN undefined_object THEN "
        "    RAISE NOTICE 'skip google_ml_integration (extension not registered)'; "
        "  WHEN feature_not_supported THEN "
        "    RAISE NOTICE 'skip google_ml_integration (extension not installed at OS level — expected on local dev)'; "
        "  WHEN insufficient_privilege THEN "
        "    RAISE NOTICE 'skip google_ml_integration (missing IAM / Cloud SQL flag — check cloudsql.enable_google_ml_integration)'; "
        "  WHEN OTHERS THEN "
        "    RAISE NOTICE 'skip google_ml_integration (unexpected error: %)', SQLERRM; "
        "END $$;"
    )

    # ===== Tables (auto-generated by Alembic) =====
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('industries',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('parent_code', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('vsic_2025', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(level=1 AND parent_code IS NULL) OR (level=2 AND parent_code IS NOT NULL)', name='ck_industry_hierarchy'),
    sa.CheckConstraint('level IN (1,2)', name='ck_industry_level'),
    sa.ForeignKeyConstraint(['parent_code'], ['industries.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('intent_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('match_kind', sa.Text(), nullable=False),
    sa.Column('complement_code', sa.Text(), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("match_kind IN ('complementarity','similarity','mixed')", name='ck_intent_match_kind'),
    sa.ForeignKeyConstraint(['complement_code'], ['intent_types.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('zalo_id', sa.Text(), nullable=True),
    sa.Column('role_title', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tax_id', sa.Text(), nullable=True),
    sa.Column('legal_type', sa.Text(), nullable=True),
    sa.Column('business_stage', sa.Text(), nullable=True),
    sa.Column('year_established', sa.SmallInteger(), nullable=True),
    sa.Column('industry_l1', sa.Text(), nullable=True),
    sa.Column('industry_l2', sa.Text(), nullable=True),
    sa.Column('employee_range', sa.Text(), nullable=True),
    sa.Column('revenue_range_vnd', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('geo_operating', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('data_source', sa.Text(), server_default=sa.text("'self_reported'"), nullable=False),
    sa.Column('verification_status', sa.Text(), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_stage IN ('moi_thanh_lap','dang_tang_truong','on_dinh','mo_rong_vung','chuyen_doi_so')", name='ck_business_stage'),
    sa.CheckConstraint("data_source IN ('self_reported','mst_lookup','admin_input')", name='ck_data_source'),
    sa.CheckConstraint("employee_range IN ('0','1_5','6_10','11_50','51_100','101_200','200_plus')", name='ck_employee_range'),
    sa.CheckConstraint("legal_type IN ('ho_kinh_doanh','doanh_nghiep_tu_nhan','cong_ty_tnhh_1tv','cong_ty_tnhh_2tv','cong_ty_co_phan','hop_tac_xa','cong_ty_hop_danh','khac')", name='ck_legal_type'),
    sa.CheckConstraint("revenue_range_vnd IN ('duoi_100_trieu','100_trieu_1_ty','1_ty_3_ty','3_ty_10_ty','10_ty_50_ty','50_ty_100_ty','100_ty_300_ty','tren_300_ty','khong_tiet_lo')", name='ck_revenue_range'),
    sa.CheckConstraint("verification_status IN ('unverified','mst_matched','manually_verified')", name='ck_verification_status'),
    sa.CheckConstraint('year_established BETWEEN 1900 AND 2100', name='ck_year_established'),
    sa.ForeignKeyConstraint(['industry_l1'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['industry_l2'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['persons.id'], name='fk_businesses_verified_by', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('business_persons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.CheckConstraint("role IN ('owner','director','sales_rep','authorized_rep')", name='ck_bp_role'),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name='ck_bp_dates'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'person_id', 'role', name='uq_business_person_role')
    )
    op.create_table('needs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('intent_type', sa.Text(), nullable=False),
    sa.Column('category_l1', sa.Text(), nullable=True),
    sa.Column('category_l2', sa.Text(), nullable=True),
    sa.Column('geo_scope', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structured_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_l1'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['category_l2'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['intent_type'], ['intent_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('intent_type', sa.Text(), nullable=False),
    sa.Column('category_l1', sa.Text(), nullable=True),
    sa.Column('category_l2', sa.Text(), nullable=True),
    sa.Column('geo_scope', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structured_attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_l1'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['category_l2'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['intent_type'], ['intent_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_person_id', sa.UUID(), nullable=True),
    sa.Column('target_business_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.Text(), nullable=False),
    sa.Column('context_offer_id', sa.UUID(), nullable=True),
    sa.Column('context_need_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("interaction_type IN ('view_profile','send_invite','accept_invite','message')", name='ck_interaction_type'),
    sa.ForeignKeyConstraint(['actor_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['context_need_id'], ['needs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['context_offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ===== Indexes =====
    op.create_index("idx_businesses_industry_l1", "businesses", ["industry_l1"])
    op.create_index("idx_businesses_industry_l2", "businesses", ["industry_l2"])
    op.create_index("idx_businesses_province", "businesses", ["province"])
    op.create_index("idx_offers_business", "offers", ["business_id"])
    op.create_index("idx_offers_intent", "offers", ["intent_type"])
    op.create_index("idx_needs_business", "needs", ["business_id"])
    op.create_index("idx_needs_intent", "needs", ["intent_type"])
    op.create_index("idx_offers_attrs", "offers", ["structured_attrs"], postgresql_using="gin")
    op.create_index("idx_needs_attrs", "needs", ["structured_attrs"], postgresql_using="gin")
    op.create_index("idx_offers_geo", "offers", ["geo_scope"], postgresql_using="gin")
    op.create_index("idx_needs_geo", "needs", ["geo_scope"], postgresql_using="gin")
    # Partial unique: at most 1 NULL role per business-person pair (Postgres: NULL ≠ NULL)
    op.execute(
        "CREATE UNIQUE INDEX uq_business_person_null_role "
        "ON business_persons (business_id, person_id) WHERE role IS NULL;"
    )

    # ===== Trigger updated_at (DB-level, runs even when bypassing ORM) =====
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
        $$ LANGUAGE plpgsql;
    """)
    for tbl in ("businesses", "persons", "offers", "needs"):
        op.execute(f"""
            CREATE TRIGGER trg_{tbl}_updated_at
            BEFORE UPDATE ON {tbl}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """)


def downgrade() -> None:
    # Drop triggers + function
    for tbl in ("businesses", "persons", "offers", "needs"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tbl}_updated_at ON {tbl}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_interactions')
    op.drop_table('offers')
    op.drop_table('needs')
    op.drop_table('business_persons')
    op.drop_table('businesses')
    op.drop_table('persons')
    op.drop_table('intent_types')
    op.drop_table('industries')
    op.drop_table('certifications')
    # ### end Alembic commands ###

    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS google_ml_integration")
    op.execute("DROP EXTENSION IF EXISTS unaccent")
    op.execute("DROP EXTENSION IF EXISTS vector")
